/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/csrf-token": {
    /** CSRFトークンを取得する */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["model.CsrfTokenResponse"];
        };
      };
    };
  };
  "/login": {
    /** 既存ユーザーのログイン処理 */
    post: {
      parameters: {
        body: {
          /** ログイン情報 */
          user: definitions["model.UserLoginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: string;
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/logout": {
    /** ユーザーのログアウト処理 */
    post: {
      responses: {
        /** OK */
        200: {
          schema: string;
        };
      };
    };
  };
  "/signup": {
    /** 新しいユーザーアカウントを作成する */
    post: {
      parameters: {
        body: {
          /** ユーザー登録情報 */
          user: definitions["model.UserSignupRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["model.UserResponse"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/tasks": {
    /** ログインユーザーのすべてのタスクを取得する */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["model.TaskResponse"][];
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** ユーザーの新しいタスクを作成する */
    post: {
      parameters: {
        body: {
          /** タスク情報 */
          task: definitions["model.TaskRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["model.TaskResponse"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/tasks/{taskId}": {
    /** 指定されたIDのタスクを取得する */
    get: {
      parameters: {
        path: {
          /** タスクID */
          taskId: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["model.TaskResponse"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** 指定されたIDのタスクを更新する */
    put: {
      parameters: {
        path: {
          /** タスクID */
          taskId: number;
        };
        body: {
          /** 更新するタスク情報 */
          task: definitions["model.TaskRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["model.TaskResponse"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** 指定されたIDのタスクを削除する */
    delete: {
      parameters: {
        path: {
          /** タスクID */
          taskId: number;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
}

export interface definitions {
  "model.CsrfTokenResponse": {
    /** @example token-string-here */
    csrf_token?: string;
  };
  "model.TaskRequest": {
    /** @example 買い物に行く */
    title: string;
  };
  "model.TaskResponse": {
    /** @example 2023-01-01T00:00:00Z */
    created_at?: string;
    /** @example 1 */
    id?: number;
    /** @example 買い物に行く */
    title?: string;
    /** @example 2023-01-01T00:00:00Z */
    updated_at?: string;
  };
  "model.UserLoginRequest": {
    /** @example user@example.com */
    email: string;
    /** @example password123 */
    password: string;
  };
  "model.UserResponse": {
    /** @example user@example.com */
    email?: string;
    /** @example 1 */
    id?: number;
  };
  "model.UserSignupRequest": {
    /** @example user@example.com */
    email: string;
    /** @example password123 */
    password: string;
  };
}

export interface operations {}

export interface external {}
